#!/usr/bin/env python
#-*- coding:utf-8 -*-

import urllib2
import sys 
import smtplib
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import quopri
from BeautifulSoup import BeautifulSoup

# hole seite
response = urllib2.urlopen('http://python.org/')
html = response.read()
soup = BeautifulSoup(html)
images = soup.findAll('img')
for img in images:
    print img['src']
links = soup.findAll('link',type='text/css')
for link in links:
    print link['type'],link['href']
scripts = soup.findAll('script')
for script in scripts:
    print script
iframes = soup.findAll('iframe')
for iframe in iframes:
    print iframe['src']
 

# ----   schreibe mtml file --------------

# Here are the email package modules we'll need

COMMASPACE = ', '

# Create the container (outer) email message.
msg = MIMEMultipart('related')
#msg['From'] = '<Saved by getpage 0.1>'
#msg['Subject'] = soup.head.title.string
#msg['Date']='Fri, 16 Mar 2012 11:13:53 +0100'
# me == the sender's email address
# family = the list of all recipients' email addresses
msg.preamble = 'This is a multi-part message in MIME format.\n'
htmltxt =MIMEText(quopri.encodestring(html), 'html')
htmltxt.add_header('Content-Transfer-Encoding', 'quoted-printable')
htmltxt.add_header('Content-Location', 'http://python.org/')
msg.attach(htmltxt)

# Send the email via our own SMTP server.
f=open(soup.head.title.string +'.mht','w')
f.write('From: <Saved by getpage 0.1>\r\n')
f.write('Subject: '+ soup.head.title.string+'\r\n')
f.write('Date: Fri, 16 Mar 2012 11:13:53 +0100\r\n')
f.write(msg.as_string())
f.close


# ermittle Bilder
# ermittle scripte
# ermittle css

    
